# Generated by Django 4.0.1 on 2022-02-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='news_previews/'),
        ),
    ]
